#ifndef RASTER2PNG_GLOBAL_H
#define RASTER2PNG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RASTER2PNG_LIBRARY)
#  define RASTER2PNGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RASTER2PNGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RASTER2PNG_GLOBAL_H
